export function isAutoGeneratedEmail(email) {
  const value = String(email || '').trim().toLowerCase();
  if (!value) return false;

  return (
    value.endsWith('@oneclick.7xbet.local') ||
    /^(google|facebook)-.+@7xbet\.local$/.test(value)
  );
}

export function getPublicEmail(email) {
  const value = String(email || '').trim().toLowerCase();
  if (!value || isAutoGeneratedEmail(value)) return '';
  return value;
}
